/*
Copyright 2019 The Stash Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/appscode/stash/apis/stash/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBackupTemplates implements BackupTemplateInterface
type FakeBackupTemplates struct {
	Fake *FakeStashV1alpha1
	ns   string
}

var backuptemplatesResource = schema.GroupVersionResource{Group: "stash.appscode.com", Version: "v1alpha1", Resource: "backuptemplates"}

var backuptemplatesKind = schema.GroupVersionKind{Group: "stash.appscode.com", Version: "v1alpha1", Kind: "BackupTemplate"}

// Get takes name of the backupTemplate, and returns the corresponding backupTemplate object, and an error if there is any.
func (c *FakeBackupTemplates) Get(name string, options v1.GetOptions) (result *v1alpha1.BackupTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(backuptemplatesResource, c.ns, name), &v1alpha1.BackupTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BackupTemplate), err
}

// List takes label and field selectors, and returns the list of BackupTemplates that match those selectors.
func (c *FakeBackupTemplates) List(opts v1.ListOptions) (result *v1alpha1.BackupTemplateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(backuptemplatesResource, backuptemplatesKind, c.ns, opts), &v1alpha1.BackupTemplateList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BackupTemplateList{ListMeta: obj.(*v1alpha1.BackupTemplateList).ListMeta}
	for _, item := range obj.(*v1alpha1.BackupTemplateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested backupTemplates.
func (c *FakeBackupTemplates) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(backuptemplatesResource, c.ns, opts))

}

// Create takes the representation of a backupTemplate and creates it.  Returns the server's representation of the backupTemplate, and an error, if there is any.
func (c *FakeBackupTemplates) Create(backupTemplate *v1alpha1.BackupTemplate) (result *v1alpha1.BackupTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(backuptemplatesResource, c.ns, backupTemplate), &v1alpha1.BackupTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BackupTemplate), err
}

// Update takes the representation of a backupTemplate and updates it. Returns the server's representation of the backupTemplate, and an error, if there is any.
func (c *FakeBackupTemplates) Update(backupTemplate *v1alpha1.BackupTemplate) (result *v1alpha1.BackupTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(backuptemplatesResource, c.ns, backupTemplate), &v1alpha1.BackupTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BackupTemplate), err
}

// Delete takes name of the backupTemplate and deletes it. Returns an error if one occurs.
func (c *FakeBackupTemplates) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(backuptemplatesResource, c.ns, name), &v1alpha1.BackupTemplate{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBackupTemplates) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(backuptemplatesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.BackupTemplateList{})
	return err
}

// Patch applies the patch and returns the patched backupTemplate.
func (c *FakeBackupTemplates) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.BackupTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(backuptemplatesResource, c.ns, name, data, subresources...), &v1alpha1.BackupTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BackupTemplate), err
}
