/*
Copyright 2019 The Stash Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/appscode/stash/apis/stash/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBackupTriggers implements BackupTriggerInterface
type FakeBackupTriggers struct {
	Fake *FakeStashV1alpha1
	ns   string
}

var backuptriggersResource = schema.GroupVersionResource{Group: "stash.appscode.com", Version: "v1alpha1", Resource: "backuptriggers"}

var backuptriggersKind = schema.GroupVersionKind{Group: "stash.appscode.com", Version: "v1alpha1", Kind: "BackupTrigger"}

// Get takes name of the backupTrigger, and returns the corresponding backupTrigger object, and an error if there is any.
func (c *FakeBackupTriggers) Get(name string, options v1.GetOptions) (result *v1alpha1.BackupTrigger, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(backuptriggersResource, c.ns, name), &v1alpha1.BackupTrigger{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BackupTrigger), err
}

// List takes label and field selectors, and returns the list of BackupTriggers that match those selectors.
func (c *FakeBackupTriggers) List(opts v1.ListOptions) (result *v1alpha1.BackupTriggerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(backuptriggersResource, backuptriggersKind, c.ns, opts), &v1alpha1.BackupTriggerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BackupTriggerList{ListMeta: obj.(*v1alpha1.BackupTriggerList).ListMeta}
	for _, item := range obj.(*v1alpha1.BackupTriggerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested backupTriggers.
func (c *FakeBackupTriggers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(backuptriggersResource, c.ns, opts))

}

// Create takes the representation of a backupTrigger and creates it.  Returns the server's representation of the backupTrigger, and an error, if there is any.
func (c *FakeBackupTriggers) Create(backupTrigger *v1alpha1.BackupTrigger) (result *v1alpha1.BackupTrigger, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(backuptriggersResource, c.ns, backupTrigger), &v1alpha1.BackupTrigger{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BackupTrigger), err
}

// Update takes the representation of a backupTrigger and updates it. Returns the server's representation of the backupTrigger, and an error, if there is any.
func (c *FakeBackupTriggers) Update(backupTrigger *v1alpha1.BackupTrigger) (result *v1alpha1.BackupTrigger, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(backuptriggersResource, c.ns, backupTrigger), &v1alpha1.BackupTrigger{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BackupTrigger), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBackupTriggers) UpdateStatus(backupTrigger *v1alpha1.BackupTrigger) (*v1alpha1.BackupTrigger, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(backuptriggersResource, "status", c.ns, backupTrigger), &v1alpha1.BackupTrigger{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BackupTrigger), err
}

// Delete takes name of the backupTrigger and deletes it. Returns an error if one occurs.
func (c *FakeBackupTriggers) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(backuptriggersResource, c.ns, name), &v1alpha1.BackupTrigger{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBackupTriggers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(backuptriggersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.BackupTriggerList{})
	return err
}

// Patch applies the patch and returns the patched backupTrigger.
func (c *FakeBackupTriggers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.BackupTrigger, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(backuptriggersResource, c.ns, name, data, subresources...), &v1alpha1.BackupTrigger{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BackupTrigger), err
}
