apiVersion: stash.appscode.com/v1alpha1
kind: Recovery
metadata:
  name: stash-demo
  namespace: default
spec:
  restic: stash-demo
  workload:
    kind: Deployment
    name: stash-demo
  volumes:
  - name: source-data
    hostPath:
      path: /data/stash-test/restic-restored

