apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-demo
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: deployment-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: stash-sidecar
subjects:
- kind: ServiceAccount
  name: deployment-demo
  namespace: default
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: daemonset-demo
  name: workload
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: daemonset-demo
      name: busybox
    spec:
      serviceAccountName: daemonset-demo
      containers:
      - command:
        - sleep
        - "3600"
        image: busybox
        imagePullPolicy: IfNotPresent
        name: busybox
        volumeMounts:
        - mountPath: /srv/host-etc
          name: host-etc
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /etc
        name: host-etc
---
apiVersion: v1
data:
  RESTIC_PASSWORD: bm90QHNlY3JldA==
kind: Secret
metadata:
  name: daemonset-secret
  namespace: default
type: Opaque
---
apiVersion: stash.appscode.com/v1alpha1
kind: Restic
metadata:
  name: daemonset-restic
  namespace: default
spec:
  selector:
    matchLabels:
      app: daemonset-demo
  fileGroups:
  - path: /srv/host-etc
    retentionPolicy:
      keepLast: 5
      prune: true
  backend:
    local:
      path: /repo
      volumeSource:
        emptyDir: {}
        name: repo
    storageSecretName: daemonset-secret
  schedule: '@every 1m'
  volumeMounts:
  - mountPath: /srv/host-etc
    name: host-etc
