/*
Copyright 2019 The Stash Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/appscode/stash/apis/stash/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBackupConfigurationTemplates implements BackupConfigurationTemplateInterface
type FakeBackupConfigurationTemplates struct {
	Fake *FakeStashV1beta1
}

var backupconfigurationtemplatesResource = schema.GroupVersionResource{Group: "stash.appscode.com", Version: "v1beta1", Resource: "backupconfigurationtemplates"}

var backupconfigurationtemplatesKind = schema.GroupVersionKind{Group: "stash.appscode.com", Version: "v1beta1", Kind: "BackupConfigurationTemplate"}

// Get takes name of the backupConfigurationTemplate, and returns the corresponding backupConfigurationTemplate object, and an error if there is any.
func (c *FakeBackupConfigurationTemplates) Get(name string, options v1.GetOptions) (result *v1beta1.BackupConfigurationTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(backupconfigurationtemplatesResource, name), &v1beta1.BackupConfigurationTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.BackupConfigurationTemplate), err
}

// List takes label and field selectors, and returns the list of BackupConfigurationTemplates that match those selectors.
func (c *FakeBackupConfigurationTemplates) List(opts v1.ListOptions) (result *v1beta1.BackupConfigurationTemplateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(backupconfigurationtemplatesResource, backupconfigurationtemplatesKind, opts), &v1beta1.BackupConfigurationTemplateList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.BackupConfigurationTemplateList{ListMeta: obj.(*v1beta1.BackupConfigurationTemplateList).ListMeta}
	for _, item := range obj.(*v1beta1.BackupConfigurationTemplateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested backupConfigurationTemplates.
func (c *FakeBackupConfigurationTemplates) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(backupconfigurationtemplatesResource, opts))
}

// Create takes the representation of a backupConfigurationTemplate and creates it.  Returns the server's representation of the backupConfigurationTemplate, and an error, if there is any.
func (c *FakeBackupConfigurationTemplates) Create(backupConfigurationTemplate *v1beta1.BackupConfigurationTemplate) (result *v1beta1.BackupConfigurationTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(backupconfigurationtemplatesResource, backupConfigurationTemplate), &v1beta1.BackupConfigurationTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.BackupConfigurationTemplate), err
}

// Update takes the representation of a backupConfigurationTemplate and updates it. Returns the server's representation of the backupConfigurationTemplate, and an error, if there is any.
func (c *FakeBackupConfigurationTemplates) Update(backupConfigurationTemplate *v1beta1.BackupConfigurationTemplate) (result *v1beta1.BackupConfigurationTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(backupconfigurationtemplatesResource, backupConfigurationTemplate), &v1beta1.BackupConfigurationTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.BackupConfigurationTemplate), err
}

// Delete takes name of the backupConfigurationTemplate and deletes it. Returns an error if one occurs.
func (c *FakeBackupConfigurationTemplates) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(backupconfigurationtemplatesResource, name), &v1beta1.BackupConfigurationTemplate{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBackupConfigurationTemplates) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(backupconfigurationtemplatesResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.BackupConfigurationTemplateList{})
	return err
}

// Patch applies the patch and returns the patched backupConfigurationTemplate.
func (c *FakeBackupConfigurationTemplates) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.BackupConfigurationTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(backupconfigurationtemplatesResource, name, data, subresources...), &v1beta1.BackupConfigurationTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.BackupConfigurationTemplate), err
}
