apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: pvc-restore-01
  namespace: demo
spec:
  runtimeSettings:
    pod:
      serviceAccountName: pvc-backup-restore
  task:
    name: pvc-restore-task
  repository:
    name: hello-repo
  target:
    ref:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: test-pvc-dest
    volumeMounts:
    - name: mount-01
      mountPath: /etc/target
  rules:
  - hosts:
    - host-0
    paths:
    - /etc/target/dir-01
    - /etc/target/dir-02
