#!/bin/bash
exec 1> >(logger -s -p daemon.info -t ${PWD##*/})
exec 2> >(logger -s -p daemon.error -t ${PWD##*/})
source /etc/envvars

echo "Starting cron..."
# sv start socklog-unix || exit 1
exec cron -f
