/*
Copyright 2019 The Stash Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	stashv1beta1 "stash.appscode.dev/stash/apis/stash/v1beta1"
	versioned "stash.appscode.dev/stash/client/clientset/versioned"
	internalinterfaces "stash.appscode.dev/stash/client/informers/externalversions/internalinterfaces"
	v1beta1 "stash.appscode.dev/stash/client/listers/stash/v1beta1"
)

// BackupConfigurationTemplateInformer provides access to a shared informer and lister for
// BackupConfigurationTemplates.
type BackupConfigurationTemplateInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.BackupConfigurationTemplateLister
}

type backupConfigurationTemplateInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewBackupConfigurationTemplateInformer constructs a new informer for BackupConfigurationTemplate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewBackupConfigurationTemplateInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredBackupConfigurationTemplateInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredBackupConfigurationTemplateInformer constructs a new informer for BackupConfigurationTemplate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredBackupConfigurationTemplateInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StashV1beta1().BackupConfigurationTemplates().List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StashV1beta1().BackupConfigurationTemplates().Watch(options)
			},
		},
		&stashv1beta1.BackupConfigurationTemplate{},
		resyncPeriod,
		indexers,
	)
}

func (f *backupConfigurationTemplateInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredBackupConfigurationTemplateInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *backupConfigurationTemplateInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&stashv1beta1.BackupConfigurationTemplate{}, f.defaultInformer)
}

func (f *backupConfigurationTemplateInformer) Lister() v1beta1.BackupConfigurationTemplateLister {
	return v1beta1.NewBackupConfigurationTemplateLister(f.Informer().GetIndexer())
}
