/*
Copyright 2019 The Stash Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	time "time"

	stashv1beta1 "github.com/appscode/stash/apis/stash/v1beta1"
	versioned "github.com/appscode/stash/client/clientset/versioned"
	internalinterfaces "github.com/appscode/stash/client/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/appscode/stash/client/listers/stash/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// BackupTemplateInformer provides access to a shared informer and lister for
// BackupTemplates.
type BackupTemplateInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.BackupTemplateLister
}

type backupTemplateInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewBackupTemplateInformer constructs a new informer for BackupTemplate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewBackupTemplateInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredBackupTemplateInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredBackupTemplateInformer constructs a new informer for BackupTemplate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredBackupTemplateInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StashV1beta1().BackupTemplates().List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StashV1beta1().BackupTemplates().Watch(options)
			},
		},
		&stashv1beta1.BackupTemplate{},
		resyncPeriod,
		indexers,
	)
}

func (f *backupTemplateInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredBackupTemplateInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *backupTemplateInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&stashv1beta1.BackupTemplate{}, f.defaultInformer)
}

func (f *backupTemplateInformer) Lister() v1beta1.BackupTemplateLister {
	return v1beta1.NewBackupTemplateLister(f.Informer().GetIndexer())
}
