apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: pvc-backup-config
  namespace: demo
spec:
  task:
    name: pvc-backup-task
  repository:
    name: hello-repo
  schedule: "0 * * * *"
  target:
    ref:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: test-pvc-source
    mountPath: /etc/target
    directories:
    - /etc/target/dir-01
    - /etc/target/dir-02
  retentionPolicy:
    keepLast: 5
    prune: true

---
apiVersion: stash.appscode.com/v1beta1
kind: BackupSession
metadata:
  name: pvc-backup-01
  namespace: demo
spec:
  backupConfiguration:
    name: pvc-backup-config